name: Run go tests
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  # GET REPO NAME
  get-repo-name:
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repo name
        run: echo "Repo name is ${{ github.repository }}"

        id: get-repo-name
        # This is the output variable
        # We can access this variable in other jobs using `needs.get-repo-name.outputs.repo-name`

  # GET USER INFOS
  get-user-infos:
    # récupérer les infos de l'utilisateur venant du repo
    needs: get-repo-name
    runs-on: ubuntu-latest
    outputs:
      user: ${{ github.actor }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get user infos
        run: echo "User infos are ${{ github.actor }}"
        id: get-user-infos

  #  RUN GO TEST
  run-go-test:
    outputs:
      outcome: ${{job.status}}
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: safebase_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./back

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: safebase_test
        run: go test -v ./test
        working-directory: ./back

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build et push de l'image back
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./back
          file: ./back/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/back:latest
        
      # 5. Build et push de l'image client
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./back
          file: ./client/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/client:latest

  # Job optionnel pour déployer sur un serveur (exemple avec SSH)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          script: |
            # Connexion au serveur et pull de la dernière image
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull $DOCKER_USERNAME/nextjs-app:latest
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d -p 3000:3000 --name nextjs-app $DOCKER_USERNAME/nextjs-app:latest


  # SEND MESSAGE
  send-chat:
    needs: [get-repo-name, get-user-infos, run-go-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        env:
          CHAT_LINK: ${{ secrets.CHAT_LINK }}

      - name: Google Chat Notification Action
        uses: SimonScholz/google-chat-action@v1.1.0
        with:
          webhookUrl: "${{ secrets.CHAT_LINK }}"
          jobStatus: ${{ needs.run-go-test.outputs.outcome }}
          title: "${{ needs.get-user-infos.outputs.user }} a créé une pull request"
          subtitle: "Pull Request sur le main || repo: ${{ needs.get-repo-name.outputs.repo-name }}"
          imageUrl: "https://github.com/${{ needs.get-user-infos.outputs.user }}.png?size=200"
          imageType: Circle
          # additionalSections: '[{"header": "Additional Section", "collapsible": true, "widgets": [{"decoratedText": {"startIcon": {"knownIcon": "STAR"},"text": "Additional Section"}}] }]'
          additionalSections: '[{"header": "Information", "collapsible": true, "widgets": [{"decoratedText": {"text": "Pull Request sur le main"}}]},{"header": "Action", "collapsible": false, "widgets": [{"decoratedText": {"text": "TEST"}}]}]'
