name: Go CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: safebase_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.1

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./back

    - name: Run tests
      env:
          DB_HOST: localhost
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: safebase_test
      run: go test -v ./test
      working-directory: ./back