name: Notif Google Chat
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  get-repo-name:
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repo name
        run: echo "Repo name is ${{ github.repository }}"

        id: get-repo-name
        # This is the output variable
        # We can access this variable in other jobs using `needs.get-repo-name.outputs.repo-name`

  get-user-infos:
    # récupérer les infos de l'utilisateur venant du repo
    needs: get-repo-name
    runs-on: ubuntu-latest
    outputs:
      user: ${{ github.actor }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get user infos
        run: echo "User infos are ${{ github.actor }}"
        id: get-user-infos

  send-chat:
    needs: [get-repo-name, get-user-infos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        env:
          CHAT_LINK: ${{ secrets.CHAT_LINK }}

      - name: Google Chat Notification Action
        uses: SimonScholz/google-chat-action@v1.1.0
        with:
          webhookUrl: "${{ secrets.CHAT_LINK }}"
          # webhookUrl: "$CHAT_LINK"
          # #this is the webhook url of the google chat room (secret works on github)
          # webhookUrl: "https://chat.googleapis.com/v1/spaces/AAAAhVObDmw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=KAmOJBi0sUbs34BJVzMTScvbFvQEiaHMpUDU-xpphms"
          ## en dure car act ne prend pas en compte les secrets
          jobStatus: ${{ job.status }}
          title: "${{ needs.get-repo-name.outputs.repo-name }}"
          subtitle: "Test de l'envoi de message sur google chat"
          imageUrl: "https://github.com/${{ needs.get-user-infos.outputs.user }}.png?size=200"
          imageType: Circle
